import type { NextPage } from "next";
import Head from "next/head";
import FeedCard from "../components/feedCard";
import useSWR from "swr";
import { Kudo } from "@slashkudos/kudos-api";
import { PropsWithChildren } from "react";
import HeaderSection from "../components/headerSection";

interface Props extends PropsWithChildren<{}> {}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Feed: NextPage<Props> = () => {
  const { data, error } = useSWR<Kudo[], any>("/api/kudos", fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>slashkudos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderSection title="Recent kudos" />
      <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        {data.map((kudo, i) => (
          <FeedCard key={i} kudo={kudo}></FeedCard>
        ))}
      </div>
    </>
  );
};

export default Feed;
